// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssigmaapi/productibit/v1/productibit.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ssigmaapi.Productibit.V1 {
  public static partial class ProductibitServiceV1
  {
    static readonly string __ServiceName = "ssigmaapi.productibit.v1.ProductibitServiceV1";

    static readonly grpc::Marshaller<global::Ssigmaapi.Productibit.V1.SensorMessage> __Marshaller_ssigmaapi_productibit_v1_SensorMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ssigmaapi.Productibit.V1.SensorMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Ssigmaapi.Productibit.V1.SensorMessage, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UploadSensor = new grpc::Method<global::Ssigmaapi.Productibit.V1.SensorMessage, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UploadSensor",
        __Marshaller_ssigmaapi_productibit_v1_SensorMessage,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ssigmaapi.Productibit.V1.ProductibitReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProductibitServiceV1</summary>
    public abstract partial class ProductibitServiceV1Base
    {
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UploadSensor(global::Ssigmaapi.Productibit.V1.SensorMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProductibitServiceV1</summary>
    public partial class ProductibitServiceV1Client : grpc::ClientBase<ProductibitServiceV1Client>
    {
      /// <summary>Creates a new client for ProductibitServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ProductibitServiceV1Client(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProductibitServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ProductibitServiceV1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ProductibitServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ProductibitServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Google.Protobuf.WellKnownTypes.Empty UploadSensor(global::Ssigmaapi.Productibit.V1.SensorMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadSensor(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UploadSensor(global::Ssigmaapi.Productibit.V1.SensorMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UploadSensor, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UploadSensorAsync(global::Ssigmaapi.Productibit.V1.SensorMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadSensorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UploadSensorAsync(global::Ssigmaapi.Productibit.V1.SensorMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UploadSensor, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ProductibitServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProductibitServiceV1Client(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ProductibitServiceV1Base serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UploadSensor, serviceImpl.UploadSensor).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProductibitServiceV1Base serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UploadSensor, serviceImpl.UploadSensor);
    }

  }
}
#endregion
