// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssigmaapi/productibit/v1/productibit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ssigmaapi.Productibit.V1 {

  /// <summary>Holder for reflection information generated from ssigmaapi/productibit/v1/productibit.proto</summary>
  public static partial class ProductibitReflection {

    #region Descriptor
    /// <summary>File descriptor for ssigmaapi/productibit/v1/productibit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProductibitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipzc2lnbWFhcGkvcHJvZHVjdGliaXQvdjEvcHJvZHVjdGliaXQucHJvdG8S",
            "GHNzaWdtYWFwaS5wcm9kdWN0aWJpdC52MRohc3NpZ21hYXBpL3R5cGUvdXNl",
            "cmFjdGl2aXR5LnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8i",
            "TgoNU2Vuc29yTWVzc2FnZRILCgN1aWQYASABKAkSMAoKYWN0aXZpdGllcxgC",
            "IAMoCzIcLnNzaWdtYWFwaS50eXBlLlVzZXJBY3Rpdml0eTJpChRQcm9kdWN0",
            "aWJpdFNlcnZpY2VWMRJRCgxVcGxvYWRTZW5zb3ISJy5zc2lnbWFhcGkucHJv",
            "ZHVjdGliaXQudjEuU2Vuc29yTWVzc2FnZRoWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eSIAQjpaOGdpdGh1Yi5jb20va2FpdG8yL3NzaWdtYWFwaWdvL3Byb2R1",
            "Y3RpYml0L3YxO3Byb2R1Y3RpYml0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ssigmaapi.Type.UseractivityReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ssigmaapi.Productibit.V1.SensorMessage), global::Ssigmaapi.Productibit.V1.SensorMessage.Parser, new[]{ "Uid", "Activities" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SensorMessage : pb::IMessage<SensorMessage> {
    private static readonly pb::MessageParser<SensorMessage> _parser = new pb::MessageParser<SensorMessage>(() => new SensorMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SensorMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ssigmaapi.Productibit.V1.ProductibitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SensorMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SensorMessage(SensorMessage other) : this() {
      uid_ = other.uid_;
      activities_ = other.activities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SensorMessage Clone() {
      return new SensorMessage(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private string uid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "activities" field.</summary>
    public const int ActivitiesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Ssigmaapi.Type.UserActivity> _repeated_activities_codec
        = pb::FieldCodec.ForMessage(18, global::Ssigmaapi.Type.UserActivity.Parser);
    private readonly pbc::RepeatedField<global::Ssigmaapi.Type.UserActivity> activities_ = new pbc::RepeatedField<global::Ssigmaapi.Type.UserActivity>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Ssigmaapi.Type.UserActivity> Activities {
      get { return activities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SensorMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SensorMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if(!activities_.Equals(other.activities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      hash ^= activities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      activities_.WriteTo(output, _repeated_activities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      size += activities_.CalculateSize(_repeated_activities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SensorMessage other) {
      if (other == null) {
        return;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      activities_.Add(other.activities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 18: {
            activities_.AddEntriesFrom(input, _repeated_activities_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
